# Generated by Django 4.1.4 on 2022-12-21 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farming_Product_List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, help_text='Ex : use 1500x500 px its suitabler', max_length=555, null=True, upload_to='media/ProductsApp')),
                ('name', models.CharField(max_length=220)),
                ('discription', models.TextField()),
            ],
        ),
    ]
