# Generated by Django 4.1.4 on 2022-12-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_farming_equpments_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farming_equpments',
            name='category',
        ),
        migrations.RemoveField(
            model_name='farming_product_list',
            name='category',
        ),
    ]
