# Generated by Django 4.1.2 on 2023-02-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_farming_equpments_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farming_product_list',
            name='rate',
            field=models.CharField(default=True, max_length=220, null=True),
        ),
    ]
