# Generated by Django 4.1.2 on 2023-02-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0008_farming_product_list_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farming_product_list',
            name='rate',
            field=models.CharField(max_length=220, null=True),
        ),
    ]
