# Generated by Django 4.1.4 on 2022-12-14 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0003_rename_flrstname_contact_form_entry_records_firstname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farming_Equpments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equpement_name', models.CharField(max_length=255)),
                ('equpement_discription', models.TextField()),
                ('equpement_image', models.ImageField(blank=True, max_length=555, null=True, upload_to='media/equpement_img')),
            ],
        ),
        migrations.CreateModel(
            name='Farming_Knowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topicName', models.CharField(max_length=255)),
                ('topic_discription', models.TextField()),
                ('cover_image', models.ImageField(blank=True, max_length=555, null=True, upload_to='media/topic_img')),
            ],
        ),
        migrations.CreateModel(
            name='Farming_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('product_discription', models.TextField()),
                ('product_image', models.ImageField(blank=True, max_length=555, null=True, upload_to='media/product_img')),
            ],
        ),
    ]
