# Generated by Django 4.1.4 on 2022-12-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0004_farming_equpments_farming_knowledge_farming_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddContents',
            new_name='Types_Of_Farming',
        ),
    ]
