# Generated by Django 4.1.4 on 2022-12-16 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0005_rename_addcontents_types_of_farming'),
    ]

    operations = [
        migrations.AddField(
            model_name='types_of_farming',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
