# Generated by Django 4.1.4 on 2022-12-17 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0006_types_of_farming_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types_of_farming',
            name='slug',
            field=models.SlugField(null=True, verbose_name=' Ex: Cotton-Farming'),
        ),
    ]
