# Generated by Django 4.1.4 on 2022-12-17 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0007_alter_types_of_farming_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='types_of_farming',
            name='slug',
            field=models.SlugField(help_text='Ex :  Cotton-Farming', null=True),
        ),
    ]
