# Generated by Django 4.1.4 on 2022-12-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0008_alter_types_of_farming_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='farming_knowledge',
            name='slug',
            field=models.SlugField(help_text='Ex : add Slugs like this in this section you can make it with your titlwe name insted of space use (-) like this (Cotton-Farming)', null=True),
        ),
        migrations.AlterField(
            model_name='farming_equpments',
            name='equpement_image',
            field=models.ImageField(blank=True, help_text='Ex : use 1500x500 px its suitabler', max_length=555, null=True, upload_to='media/equpement_img'),
        ),
        migrations.AlterField(
            model_name='farming_knowledge',
            name='cover_image',
            field=models.ImageField(blank=True, help_text='Ex : use 1500x500 px its suitabler', max_length=555, null=True, upload_to='media/topic_img'),
        ),
        migrations.AlterField(
            model_name='farming_product',
            name='product_image',
            field=models.ImageField(blank=True, help_text='Ex : use 1500x500 px its suitabler', max_length=555, null=True, upload_to='media/product_img'),
        ),
        migrations.AlterField(
            model_name='types_of_farming',
            name='Images',
            field=models.ImageField(blank=True, help_text='Ex : use 1500x500 px its suitabler', max_length=555, null=True, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='types_of_farming',
            name='slug',
            field=models.SlugField(help_text='Ex : add Slugs like this in this section you can make it with your titlwe name insted of space use (-) like this (Cotton-Farming)', null=True),
        ),
        migrations.AlterField(
            model_name='types_of_farming',
            name='title',
            field=models.CharField(help_text='Ex : Add Title name at least 2 words remember this word not a single letter', max_length=255, null=True),
        ),
    ]
