# Generated by Django 4.1.4 on 2022-12-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0009_farming_knowledge_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farming_product',
            old_name='product_discription',
            new_name='Discription',
        ),
        migrations.RenameField(
            model_name='farming_product',
            old_name='product_image',
            new_name='Images',
        ),
        migrations.RenameField(
            model_name='farming_product',
            old_name='product_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='farming_equpments',
            name='slug',
            field=models.SlugField(help_text='Ex : add Slugs like this in this section you can make it with your titlwe name insted of space use (-) like this (Cotton-Farming)', null=True),
        ),
        migrations.AddField(
            model_name='farming_product',
            name='slug',
            field=models.SlugField(help_text='Ex : add Slugs like this in this section you can make it with your titlwe name insted of space use (-) like this (Cotton-Farming)', null=True),
        ),
    ]
