# Generated by Django 4.1.4 on 2022-12-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0011_rename_discription_farming_product_product_discription_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='farming_product',
            old_name='slug',
            new_name='slug1',
        ),
    ]
