# Generated by Django 4.1.4 on 2022-12-19 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0012_rename_slug_farming_product_slug1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farming_equpments',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='farming_knowledge',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='farming_product',
            name='slug1',
        ),
    ]
