# Generated by Django 4.1.4 on 2022-12-20 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0014_category_farming_equpments_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farming_equpments',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='FarmApp.category'),
        ),
    ]
