# Generated by Django 4.1.4 on 2022-12-21 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0015_alter_farming_equpments_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Farming_Equpments',
        ),
    ]
