# Generated by Django 4.1.4 on 2022-12-21 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_alter_farming_equpments_category_and_more'),
        ('FarmApp', '0016_delete_farming_equpments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
