# Generated by Django 4.1.2 on 2023-02-17 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FarmApp', '0017_delete_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Farming_Knowledge',
            new_name='Flower_farming',
        ),
    ]
