# Generated by Django 4.1.4 on 2022-12-21 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_remove_farming_equpments_category_and_more'),
        ('Category', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
